providers = ['deno']
buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1741046653'


[start]
cmd = 'deno run --allow-all --no-lock ./bestpass/main.ts'


[variables]
NIXPACKS_METADATA = 'deno'
[phases.setup]
nixPkgs = ['deno','sqlite']
nixOverlays = []
nixpkgsArchive = '5148520bfab61f99fd25fb9ff7bfbb50dad3c9db'
